### ISSUE TITLE
API-Dcocumentation

### ISSUE THREAD

**Issue by ybroeker** [botorabi/Meet4Eat#14]
Add API-Dcocumentation

Maybe Swagger?

**Comment by ybroeker** [comment]
(small) Swagger-Example:
https://editor.swagger.io/?url=https://gist.githubusercontent.com/anonymous/16b1164678d970cbeef66c96df99477a/raw/2f1522f47871116d86a5b930215f97078481690e/swagger-m4e.yaml

**Comment by botorabi** [comment]
Swagger was integrated into develop branch
