### ISSUE TITLE
Logger logt nur als INFO

### ISSUE THREAD

**Issue by ybroeker** [botorabi/Meet4Eat#5]

**Comment by botorabi** [comment]
Das ist an sich so gewollt. Die Anwendungs-Logs werden alle durch logger's INFO Logs ausgegeben. Es gibt auch keine 100%ige Entsprechung im Logger für "Verbose", "Debug" und "Error".

**Comment by ybroeker** [comment]
Damit verliert man aber massiv an Übersichtlichkeit in den und Benutzbarkeit der Logs...

Aktuell sehen die so aus:
`[#|2017-12-18T22:18:59.352+0000|INFO|glassfish 5.0|(net.m4e) |_ThreadID=50;_ThreadName=AutoDeployer;_TimeMillis=1513635539352;_LevelValue=800;|`
` [I] (18.Dec.2017 22:18:59) ContextListener: Starting the servlet container|#]`

Mit dem normalem Logging sähen sie so aus, ohne das irgendeine der enthaltenen Informationen verloren geht:

`[#|2017-12-18T22:18:59.352+0000|INFO|glassfish 5.0|net.m4e.system.core. ContextListener |_ThreadID=50;_ThreadName=AutoDeployer;_TimeMillis=1513635539352;_LevelValue=800;|`
`Starting the servlet container|#]`


- Zeit ist doppelt vorhanden, einmal im dem üblichen Format, einmal anders formatiert.
- Log-Level ist doppelt vorhanden, einmal als String (`INFO`), einmal in kurz (`I`). Ersteres ist dabei intern deutlich aussagekräftiger; es hat eine Sortierung und Repräsentation als Zahlenwert, man kann den Logger direkt filtern lassen und zB verschiedene Level an verschiedenen Stellen ausgeben.
Außerdem hätte man mehr Level zu verfügung (die eben gebräuchlich und durch Sortierung auch aussagekräftiger sind)
- der TAG wird im wesentlichen in zwei geteilt, einmal das `net.m4e`-Prefix, einmal der Klassenname.
Folgt man da dem üblichen, gewinnt man noch mal an Übersichtlichkeit, weil man jeweils das gesamte Package als TAG angegeben hat - was sowohl Filtern nach Klassennamen, als auch Prefix erlaubt, aber zusätzlich noch granulärer ist

Das Format jedes Punktes (Zeit, Level, Tag, ...) kann man, wenn das Standard-format nicht passend sein sollte, beliebig anpassen, intern ist das immer noch als üblicher LogRecord repräsentiert (sodass man die Vorteile dessen nicht verliert, bei gleichzeitig gewünschtem Format).

Als Level hätte man `SEVERE,WARNING,INFO,CONFIG,FINE,FINER,FINEST`, anstatt von `verbose,info,error,warning,debug`
Entsprechungen dürften etwa sein (nach Level-Javadoc und geloggten Messages):
- `error` = `SEVERE`
- `warning` = `WARNING`
- `info` = `CONFIG`/`INFO`
- `debug` = `FINE `
- `verbose` = `FINER`

**Comment by botorabi** [comment]
Das klingt vernünftig, wir können entsprechende Anpassungen vornehmen. Es wäre gut, wenn die Logs dennoch gekennzeichnet werden könnten, die von der Anwendung kommen, siehe die (bereits gefilterte) Beispielausgabe hier:

```
WARN:   WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class org.glassfish.cdi.transaction.TransactionalInterceptorSupports is deprecated from CDI 1.1!
WARN:   WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$JaxRsParamProducer is deprecated from CDI 1.1!
WARN:   WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class org.glassfish.jersey.ext.cdi1x.servlet.internal.CdiExternalRequestScope is deprecated from CDI 1.1!
WARN:   WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class com.sun.faces.flow.FlowDiscoveryCDIHelper is deprecated from CDI 1.1!
Info:   Initializing Soteria 1.0 for context '/m4e'
Info:   Registering WebSocket filter for url pattern /*
Info:   Initializing Mojarra 2.3.2 ( 20170627-2139 e63598abf2ed2bb1a24674f308a734e0dce18a72) for context '/m4e'
Info:   [I] (19.Dec.2017 10:14:20) ContextListener: Starting the servlet container
Info:   [I] (19.Dec.2017 10:14:20) AppConfiguration: Successfully loaded account registration configuration
Info:   [D] (19.Dec.2017 10:14:20) AuthFilter: Initializing filter: basePath(m4e) | publicBasePath(m4e/public) | protectedBasePath(m4e/webresources)
Info:   [D] (19.Dec.2017 10:14:20) AuthFilter: Setup authorization check for protected path: m4e/webresources
Info:   [I] (19.Dec.2017 10:14:20) AuthChecker: Initializing authorization checker
Info:   [D] (19.Dec.2017 10:14:20) AuthChecker:  adding rules for bean class net.m4e.update.UpdateCheckEntityFacadeREST
Info:   [D] (19.Dec.2017 10:14:20) AuthChecker:    adding rule: Resource path: '/rest/update | Access roles [GET]: ADMIN
Info:   [D] (19.Dec.2017 10:14:20) AuthChecker:    adding rule: Resource path: '/rest/update/count | Access roles [GET]: ADMIN
Info:   [D] (19.Dec.2017 10:14:20) AuthChecker:    adding rule: Resource path: '/rest/update/create | Access roles [POST]: ADMIN

```

Wie du siehst, vermischen sich die Ausgaben aus der Runtime-Umgebung und die aus der Anwendung selbst. Es wäre gut, auf den ersten Blick die Anwendungsausgaben zu erkennen.

**Comment by ybroeker** [comment]
In dem Beispiel ist der Teil, der die Quelle enthält, rausgefiltert. 
Man kann den Log einfach nach den Tags filtern, dann bekommt man nur die relevanten Teile.

Außerdem könnte man zB die Logs in unterschiedliche Ausgaben schreiben lassen.

**Comment by botorabi** [comment]
Alle Logs wurden nun umgestellt.
